import type { Metadata } from 'next';
import { Inter } from '@next/font/google';
import '@/styles/reset.css';
import '@/styles/global.css';
import Header from '@/components/header';
import Footer from '@/components/footer';

const interFont = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={interFont.className}>
      <body className='container'>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
